### ISSUE TITLE
A .git folder is required for Sherlock to run

### ISSUE THREAD

**Issue by MutedFox** [DCS-Sherlock/Sherlock#20]
If you download a ZIP of Sherlock, it won't create a .git folder (which is correct). However, without a .git folder, Sherlock does not build properly because of grgit commands in build.gradle. It tells you that grgit is a null object, because the grgit gradle plugin works by autodetecting the .git folder.

If you use git commands to clone the project, you it will construct the .git folder properly, but essentially this issue prevents a "release" Sherlock from working. At the very least, if I'm wrong, the build instructions as-is are not correct if you download Sherlock in this way.

**Comment by jamesmturner** [comment]
Fixed in https://github.com/DCS-Sherlock/Sherlock/commit/044893e9a8377e1d584c4d2d9af9b4c067de023d
